controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - palm_to_left_finger
      - palm_to_right_finger
initial:  # Define initial robot poses per group
  - group: arm
    pose: home
  - group: fake_gripper
    pose: open